name: Build Rust iOS Static Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios-static-lib:
    runs-on: macos-latest  # 必须用 macOS（iOS 交叉编译需要 Xcode 工具链）

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain with iOS target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios
          components: rust-std  # 确保标准库可用（通常默认包含）

      - name: Build static library for iOS (ARM64)
        run: cargo build --release --target aarch64-apple-ios

      - name: Verify static library exists
        run: |
          ls -l target/aarch64-apple-ios/release/
          find target/aarch64-apple-ios/release -name "*.a" -type f

      - name: Upload static library artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-aarch64-static-lib
          path: target/aarch64-apple-ios/release/*.a
          if-no-files-found: error  # 如果没找到 .a 文件则失败